"""
This module contains a list of initial prompts that can be used as input for text generation tasks, 
such as generating responses using a pre-trained language model or in our project to collect users answers.
"""

initial_prompts = [
    "How have you been feeling lately?",
    "What's been on your mind recently?",
    "Tell me about a situation that has been causing you stress or anxiety.",
    "How would you describe your overall mood and emotional state?",
    "Have you noticed any changes in your sleep patterns or appetite?",
    "What are some activities or hobbies that you enjoy and find fulfilling?",
    "How would you rate your overall life satisfaction at the moment?",
    "Can you describe your support system and relationships with friends and family?",
    "Have you experienced any significant life changes or transitions recently?",
    "How do you typically cope with stress or difficult emotions?",
    "What are your thoughts on seeking professional help or therapy?",
    "Have you ever experienced feelings of sadness, hopelessness, or lack of motivation?",
    "Can you describe any negative thought patterns or irrational beliefs that might be impacting your mental health?",
    "Have you ever experienced panic attacks or intense anxiety?",
    "How do you handle conflicts or disagreements in your relationships?",
    "Have you ever struggled with self-esteem or body image issues?",
    "What are your thoughts on mindfulness or meditation practices?",
    "Have you ever experienced trauma or traumatic events in your life?",
    "How do you typically handle anger or frustration?",
    "Have you ever had thoughts of self-harm or suicidal ideation?",
    "What are your goals or aspirations for the future?",
    "How do you typically handle stress or pressure at work or school?",
    "Have you ever experienced issues with substance abuse or addiction?",
    "How would you describe your overall physical health and well-being?",
    "Have you ever experienced feelings of loneliness or isolation?",
    "What are your thoughts on seeking support from a therapist or counselor?",
    "Have you ever experienced intrusive thoughts or obsessive behaviors?",
    "How do you typically handle major life transitions or changes?",
    "Have you ever experienced issues with procrastination or lack of motivation?",
    "What are your thoughts on setting boundaries in relationships?",
    "Have you ever experienced feelings of guilt or shame?",
    "How do you typically handle criticism or rejection?",
    "Have you ever experienced issues with anger management or impulse control?",
    "What are your thoughts on practicing self-care and self-compassion?",
    "Have you ever experienced issues with anxiety or worry about the future?",
    "How do you typically handle uncertainty or lack of control?",
    "Have you ever experienced issues with perfectionism or unrealistic expectations?",
    "What are your thoughts on seeking support from a support group or online community?",
    "Have you ever experienced issues with decision-making or indecisiveness?",
    "How do you typically handle stress or pressure in social situations?",
    "Have you ever experienced issues with low self-confidence or self-doubt?",
    "What are your thoughts on practicing gratitude or positive affirmations?",
    "Have you ever experienced issues with emotional regulation or mood swings?",
    "How do you typically handle conflicts or disagreements with authority figures?",
    "Have you ever experienced issues with procrastination or time management?",
    "What are your thoughts on seeking support from a life coach or mentor?",
    "Have you ever experienced issues with anxiety or worry about the past?",
    "How do you typically handle stress or pressure in romantic relationships?",
    "Have you ever experienced issues with self-sabotaging behaviors or negative self-talk?",
    "What are your thoughts on practicing mindfulness or present-moment awareness?",
    "Have you ever experienced issues with anxiety or worry about your physical health?",
    "How do you typically handle stress or pressure related to finances or money?",
    "Have you ever experienced issues with anxiety or worry about your career or job?",
    "What are your thoughts on seeking support from a spiritual or religious community?",
    "Have you ever experienced issues with anxiety or worry about your personal safety?",
    "How do you typically handle stress or pressure related to parenting or family responsibilities?",
    "Have you ever experienced issues with anxiety or worry about your living situation?",
    "What are your thoughts on seeking support from a life coach or career counselor?",
    "Have you ever experienced issues with anxiety or worry about your academic performance?",
    "How do you typically handle stress or pressure related to personal goals or achievements?",
    "Have you ever experienced issues with anxiety or worry about your social life or relationships?",
    "What are your thoughts on seeking support from a nutritionist or fitness coach?",
    "Have you ever experienced issues with anxiety or worry about your appearance or body image?",
    "How do you typically handle stress or pressure related to your personal values or beliefs?",
    "Have you ever experienced issues with anxiety or worry about your sexual orientation or gender identity?",
    "What are your thoughts on seeking support from a life coach or personal development coach?",
    "Have you ever experienced issues with anxiety or worry about your cultural or ethnic identity?",
    "How do you typically handle stress or pressure related to your personal growth or self-improvement?",
    "Have you ever experienced issues with anxiety or worry about your environmental impact or sustainability?",
    "What are your thoughts on seeking support from a life coach or relationship coach?",
    "Have you ever experienced issues with anxiety or worry about your political or social views?",
    "How do you typically handle stress or pressure related to your personal values or ethics?",
    "Have you ever experienced issues with anxiety or worry about your personal safety or security?",
    "What are your thoughts on seeking support from a life coach or personal finance coach?",
    "Have you ever experienced issues with anxiety or worry about your personal freedom or independence?",
    "How do you typically handle stress or pressure related to your personal goals or aspirations?",
    "Have you ever experienced issues with anxiety or worry about your personal growth or self-actualization?",
    "What are your thoughts on seeking support from a life coach or personal development coach?",
    "Have you ever experienced issues with anxiety or worry about your personal legacy or impact on the world?",
    "How do you typically handle stress or pressure related to your personal relationships or social connections?",
    "Have you ever experienced issues with anxiety or worry about your personal identity or sense of self?",
    "What are your thoughts on seeking support from a life coach or personal branding coach?",
    "Have you ever experienced issues with anxiety or worry about your personal purpose or meaning in life?",
    "How do you typically handle stress or pressure related to your personal growth or self-improvement?",
    "Have you ever experienced issues with anxiety or worry about your personal values or beliefs?",
    "What are your thoughts on seeking support from a life coach or personal development coach?",
    "Have you ever experienced issues with anxiety or worry about your personal goals or aspirations?",
    "How do you typically handle stress or pressure related to your personal relationships or social connections?",
    "Have you ever experienced issues with anxiety or worry about your personal identity or sense of self?",
    "What are your thoughts on seeking support from a life coach or personal branding coach?",
    "Have you ever experienced issues with anxiety or worry about your personal purpose or meaning in life?",
    "How do you typically handle stress or pressure related to your personal growth or self-improvement?",
    "Have you ever experienced issues with anxiety or worry about your personal values or beliefs?"
]
